_target_: model.dinov2.CustomDINOv2
model_name: dinov2_vitl14
descriptor_width_size: 640
checkpoint_dir: ./checkpoints/dinov2/
token_name: x_norm_clstoken
image_size: 224
chunk_size: 16
validpatch_thresh: 0.5