[project]
name = "sam6d-pointnet2"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["torch"]

[build-system]
requires = ["setuptools", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["sam6d.pointnet2"]

[tool.setuptools.package-dir]
"sam6d.pointnet2" = "src/sam6d/pointnet2"